version: '3'
services: 
  mongodb:
    image:  mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    env_file: mongodb.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongodb_user}
      - MONGO_INITDB_ROOT_PASSWORD=${mongodb_password}
  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file: mongodb.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongodb_user}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongodb_password}
      - ME_CONFIG_MONGODB_SERVER=mongodb
